{
  pkgs,
}:
let
  codespaceDaemons = [
    pkgs.python311Packages.supervisor
    pkgs.docker
    pkgs.socat
    pkgs.tailscale
    (pkgs.python3.withPackages (python-pkgs: [
      python-pkgs.chromadb
    ]))
  ];
  cli = [
    pkgs.direnv
    pkgs.devbox
    pkgs.nixfmt
    pkgs.opencode
    pkgs.azure-cli
    pkgs.zsh
    pkgs.neovim
    pkgs.wezterm
    pkgs.tmux
    pkgs.sesh
    pkgs.git
    pkgs.delta
    pkgs.gnupg
    pkgs.pass
    pkgs.pinentry-curses
    pkgs.docker-credential-helpers
    pkgs.gh
    pkgs.man
    pkgs.tealdeer
    pkgs.bottom
    pkgs.procs
    pkgs.curl
    pkgs.xh
    pkgs.traceroute
    pkgs.iproute2
    pkgs.netcat
    # Added for Yocto support
    pkgs.gnutar
    pkgs.zstd
    pkgs.bzip2
    pkgs.xz
    pkgs.patch
    pkgs.diffstat
    pkgs.chrpath
    pkgs.cpio
    pkgs.file
    pkgs.gawk
    pkgs.wget
    pkgs.perl
    # End added for Yocto support
    pkgs.gzip
    pkgs.zip
    pkgs.unzip
    pkgs.rsync
    pkgs.less
    pkgs.util-linux
    # Base-devel? https://archlinux.org/packages/core/any/base-devel/
    pkgs.gcc
    pkgs.clang-tools
    pkgs.cmake
    pkgs.gnumake
    # end base-deel
    pkgs.bind
    pkgs.rustup
    pkgs.ripgrep
    pkgs.fzf
    pkgs.bat
    pkgs.fd
    pkgs.eza
    pkgs.zoxide
    pkgs.stow
    pkgs.parallel
    pkgs.buildkit
    pkgs.stylua
    pkgs.prettier
    pkgs.mermaid-cli
    pkgs.shellcheck
    pkgs.go
    pkgs.gopls
    pkgs.delve
    pkgs.pyenv
    pkgs.poetry
    pkgs.pipenv
    pkgs.pre-commit
    pkgs.ruff
    pkgs.uv
    pkgs.ty
    pkgs.shfmt
    pkgs.bun
    pkgs.markdownlint-cli
    pkgs.ruby
    pkgs.kubectl
    pkgs.eksctl
    pkgs.kubernetes-helm
    pkgs.k9s
    pkgs.kustomize
    pkgs.oras
    pkgs.fluxcd
    pkgs.kubeconform
    pkgs.vault
    pkgs.tree
    pkgs.jq
    pkgs.yq-go
    pkgs.awscli2
    pkgs.nodejs
    pkgs.yarn
    pkgs.google-cloud-sdk
    pkgs.jfrog-cli
    pkgs.act
    pkgs.terraform-ls
    pkgs.terraform-docs
    pkgs.tfsec
    pkgs.tflint
    pkgs.terraformer
    pkgs.infracost
    pkgs.github-release
    pkgs.golangci-lint
    pkgs.yamllint
    (pkgs.python3.withPackages (python-pkgs: [
      python-pkgs.python-lsp-server
      python-pkgs.pip
      python-pkgs.pipx
      python-pkgs.mypy
      python-pkgs.pynvim
      python-pkgs.debugpy
      python-pkgs.pytest
      python-pkgs.pylint
      python-pkgs.flake8
      python-pkgs.ujson
    ]))
    pkgs.lefthook
    pkgs.ast-grep
    pkgs.mariadb
    pkgs.pkg-config
    pkgs.plantuml
    pkgs.vectorcode
    pkgs.appfire-cli
    # pkgs.terraform
    pkgs.tenv
    pkgs.kind
    pkgs.hugo
    pkgs.syft
    pkgs.grype
  ];
in
{
  inherit cli codespaceDaemons;

  daemons = codespaceDaemons;

  all = codespaceDaemons ++ cli;
}
