name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/seth-docker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom.spdx.json
          image: ghcr.io/${{ github.repository_owner }}/seth-docker:latest

      - name: Upload SBOM as release asset
        uses: actions/upload-artifact@v4
        with:
          name: sbom.spdx
          path: sbom.spdx.json

      - name: Extract nix store
        run: |
          container_id=$(docker create "ghcr.io/${{ github.repository_owner }}/seth-docker:latest")
          docker cp "$container_id:/nix/store/" "./store"

      - name: Generate Nix store SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: nix-sbom.spdx.json
          path: "./store"

      - name: Upload Nix SBOM as release asset
        uses: actions/upload-artifact@v4
        with:
          name: nix-sbom.spdx
          path: nix-sbom.spdx.json

      - name: Scan SBOMs
        uses: intel/cve-bin-tool-action@main
        with:
          scan_mode: sbom-only
