name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v13

      - name: Build Docker image
        run: |
          nix \
          --extra-experimental-features nix-command \
          --extra-experimental-features nix-command flakes \
          build .#docker
          docker load < ./result

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag seth-docker:latest ghcr.io/${{ github.repository_owner }}/seth-docker:latest
          docker push ghcr.io/${{ github.repository_owner }}/seth-docker:latest
