name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - uses: DeterminateSystems/flake-checker-action@v3
      - name: Build Docker image
        run: |
          nix \
          --extra-experimental-features nix-command \
          --extra-experimental-features flakes \
          build .#docker
          docker load < ./result

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag seth-docker ghcr.io/${{ github.repository_owner }}/seth-docker:latest
          docker push ghcr.io/${{ github.repository_owner }}/seth-docker:latest
